test_format = 1.0

[default]

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.export = "none"
    args.mypads = 0
    args.useldap = 0
    args.password = "##SuperAdminPassword##"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4d613658.name = "1.8.17"


[with_mypads]
    args.export = "libreoffice"
    args.mypads = 1
    args.useldap = 1
    only = ["install.root"]

[with_abiword]
    args.export = "abiword"
    args.mypads = 0
    args.useldap = 0
    only = ["install.root"]

[with_libreoffice]
    args.export = "libreoffice"
    args.mypads = 0
    args.useldap = 0
    only = ["install.root"]
