test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.export = "libreoffice"
    args.mypads = 1
    args.useldap = 1
    args.password = "admin!42"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4d613658.name = "Upgrade from 1.8.17"


# This is an additional test suite
#[without_mypads]
#    args.export = "libreoffice"
#    args.mypads = 0
#    args.useldap = 0
#    only = ["install.root"]

#[with_abiword]
#    args.export = "abiword"
#    args.mypads = 1
#    args.useldap = 1
#    only = ["install.root"]

#[without_export]
#    args.export = "none"
#    args.mypads = 1
#    args.useldap = 0
#    only = ["install.root"]
